apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres5
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    repoURL: https://gitlab.com/oawofolu/postgres-repo.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: data-samples-w02-s001
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
