apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-httpproxy
  namespace: minio
spec:
  virtualhost:
    fqdn: minio.mytanzu.ml
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: minio
      port: 9000
    
