apiVersion: v1
kind: Secret
metadata:
  name: pg-minio-secret
type: generic
stringData:
  bucket: pgbackups
  region: us-east-2
  endpoint: ${DATA_E2E_MINIO_URL}
  key: ${DATA_E2E_MINIO_ACCESS_KEY}
  keySecret: ${DATA_E2E_MINIO_SECRET_KEY}
  verifyTLS: "false"
  uriStyle: "path"

---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: pginstance-1
spec:
  storageClassName: generic
  highAvailability:
    enabled: true
  backupLocationSecret:
    name: pg-minio-secret