apiVersion: v1
kind: Secret
metadata:
  name: pg-minio-secret
type: generic
stringData:
  bucket: pgbackups
  region: us-east-2
  endpoint: minio.mytanzu.ml
  key: PMi0YICflE8ZjCQlFAw2
  keySecret: pTM99bLNCc3zgXn2jcgknjcjxCKETBhZSXzWVBH5
  verifyTLS: "false"
  uriStyle: "path"

---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: pginstance-1
spec:
  storageClassName: generic
  highAvailability:
    enabled: true
  backupLocationSecret:
    name: pg-minio-secret